// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'bridge.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `HubState`, `STATE`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`

Future<void> startHub(
        {required String databaseDirectory,
        String? username,
        String? fcmToken,
        String? backendAddress}) =>
    RustLib.instance.api.crateBridgeStartHub(
        databaseDirectory: databaseDirectory,
        username: username,
        fcmToken: fcmToken,
        backendAddress: backendAddress);

Future<void> registerUser(
        {required String username,
        String? fcmToken,
        required String backendAddress,
        required String databaseDirectory}) =>
    RustLib.instance.api.crateBridgeRegisterUser(
        username: username,
        fcmToken: fcmToken,
        backendAddress: backendAddress,
        databaseDirectory: databaseDirectory);

Future<MessageModel> sendMessage(
        {required String recipient, required String text}) =>
    RustLib.instance.api
        .crateBridgeSendMessage(recipient: recipient, text: text);

Future<List<MessageModel>> getAllMessages() =>
    RustLib.instance.api.crateBridgeGetAllMessages();

Stream<MessageModel> subscribeMessages() =>
    RustLib.instance.api.crateBridgeSubscribeMessages();

Future<void> startMockServer({required int port}) =>
    RustLib.instance.api.crateBridgeStartMockServer(port: port);

@freezed
sealed class BridgeError with _$BridgeError implements FrbException {
  const BridgeError._();

  const factory BridgeError.registrationFailed(
    String field0,
  ) = BridgeError_RegistrationFailed;
  const factory BridgeError.initializationFailed(
    String field0,
  ) = BridgeError_InitializationFailed;
  const factory BridgeError.messageSendFailed(
    String field0,
  ) = BridgeError_MessageSendFailed;
}

class MessageModel {
  final String sender;
  final String receiver;
  final PlatformInt64 dbRecvTime;
  final MessageState state;
  final String text;

  const MessageModel({
    required this.sender,
    required this.receiver,
    required this.dbRecvTime,
    required this.state,
    required this.text,
  });

  @override
  int get hashCode =>
      sender.hashCode ^
      receiver.hashCode ^
      dbRecvTime.hashCode ^
      state.hashCode ^
      text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageModel &&
          runtimeType == other.runtimeType &&
          sender == other.sender &&
          receiver == other.receiver &&
          dbRecvTime == other.dbRecvTime &&
          state == other.state &&
          text == other.text;
}

enum MessageState {
  sending,
  sent,
  delivered,
  read,
  ;
}
