[package]
name = "gossamer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
blake2 = "0.11.0"
ed25519-dalek = { version = "3.0.0", features = ["rand_core", "serde", "zeroize"] }
prost = "0.14.4"
proto = { path = "../proto/" }
protocol = { path = "../protocol/" }
rusqlite = { version = "0.37.0", features = [] }
tokio = { version = "1.44.1", features = ["rt-multi-thread", "macros", "fs", "signal"] }
tokio-rusqlite = { version = "0.7.0", features = [] }
tonic = "0.14.6"
tonic-reflection = { version = "0.14.6", features = ["server"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
xdg = "3.0.0"
hex = "0.4.3"

[dev-dependencies]
rand = "0.10.2"

