[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.104"
base64 = "0.23.1"
blake2 = "0.11.0"
chacha20poly1305 = "0.11.0"
ed25519-dalek = { version = "3.0.0", features = [
	"rand_core",
	"serde",
	"zeroize",
] }
futures = "0.3.34"
gcp_auth = { version = "0.12.7", features = ["webpki-roots"] }
gossamer = { path = "../gossamer/" }
prost = "0.14.4"
proto = { path = "../proto/" }
protocol = { path = "../protocol/" }
reqwest = { version = "0.13", default-features = false, features = [
	"json",
	"rustls-no-provider",
] }
rusqlite = { version = "0.37.0", features = [] }
rustls = { version = "0.23.43", default-features = false, features = ["ring", "std"] }
sentry = { version = "0.49.2", default-features = false, features = [
	"reqwest",
	"rustls-no-provider",
	"backtrace",
	"contexts",
	"panic",
] }
serde_json = "1.0.151"
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }
tokio-rusqlite = { version = "0.7.0", features = [] }
tokio-stream = "0.1.19"
tonic = "0.14.6"
tonic-reflection = { version = "0.14.6", features = ["server"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
x25519-dalek = { version = "3.0.0", features = [
	"getrandom",
	"static_secrets",
	"reusable_secrets",
	"serde",
	"zeroize",
] }
xdg = "3.0.0"

[dev-dependencies]
client = { path = "../client/" }
rand = "0.10.2"

