// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMPR90xX3ReY76WWhpvlFG35ddYWoDzbU',
    appId: '1:961697365248:web:269819db932fb4d0efc7e5',
    messagingSenderId: '961697365248',
    projectId: 'brongnal',
    authDomain: 'brongnal.firebaseapp.com',
    storageBucket: 'brongnal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ4AnEz45sLAWmCfBzX1d-YjjijVnuT5k',
    appId: '1:961697365248:android:128f976c6b217c0cefc7e5',
    messagingSenderId: '961697365248',
    projectId: 'brongnal',
    storageBucket: 'brongnal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC40vPCipcBWsE9HsccwO7sPjY74anyKwo',
    appId: '1:961697365248:ios:e3498e7fe566ab92efc7e5',
    messagingSenderId: '961697365248',
    projectId: 'brongnal',
    storageBucket: 'brongnal.firebasestorage.app',
    iosBundleId: 'com.example.brongnalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC40vPCipcBWsE9HsccwO7sPjY74anyKwo',
    appId: '1:961697365248:ios:e3498e7fe566ab92efc7e5',
    messagingSenderId: '961697365248',
    projectId: 'brongnal',
    storageBucket: 'brongnal.firebasestorage.app',
    iosBundleId: 'com.example.brongnalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMPR90xX3ReY76WWhpvlFG35ddYWoDzbU',
    appId: '1:961697365248:web:0f3e12787c27747defc7e5',
    messagingSenderId: '961697365248',
    projectId: 'brongnal',
    authDomain: 'brongnal.firebaseapp.com',
    storageBucket: 'brongnal.firebasestorage.app',
  );
}
