[package]
name = "protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
base64 = "0.22.1"
blake2 = "0.11.0"
chacha20poly1305 = "0.11.0"
ed25519-dalek = { version = "3.0.0", features = ["rand_core", "serde", "zeroize"] }
hkdf = "0.13.0"
num_enum = "0.7.3"
serde = { version = "1.0.219", features = ["derive"] }
sha2 = "0.11.0"
thiserror = "1.0.69"
x25519-dalek = { version = "3.0.0", features = ["getrandom", "static_secrets", "reusable_secrets", "serde", "zeroize"] }

[dev-dependencies]
ary = "0.1.0"
rand = "0.10.2"

