display_name: Brongnal
package_name: brongnal

maintainer:
  name: Brennan Tracy
  email: brennantracy4@gmail.com

priority: optional

section: x11

installed_size: 15700

dependencies:

essential: false

icon: linux/assets/brongnal_icon.png

postuninstall_scripts:
  - echo "Sorry to see you go."

keywords:
  - Signal
  - E2EE

generic_name: E2EE Messaging App

categories:
  - Messaging
  - Utility

startup_notify: true

